INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Alice', 'hello');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Bob', 'world');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Chuck', 'hello_world');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Daisy', 'world_hello');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Ellis', 'hello');

INSERT INTO CHATROOMS(NAME, OWNER) VALUES ('Java', (SELECT ID FROM USERS WHERE LOGIN='Alice'));
INSERT INTO CHATROOMS(NAME, OWNER) VALUES ('Random', (SELECT ID FROM USERS WHERE LOGIN='Daisy'));
INSERT INTO CHATROOMS(NAME, OWNER) VALUES ('Piscine', (SELECT ID FROM USERS WHERE LOGIN='Chuck'));
INSERT INTO CHATROOMS(NAME, OWNER) VALUES ('General', (SELECT ID FROM USERS WHERE LOGIN='Chuck'));
INSERT INTO CHATROOMS(NAME, OWNER) VALUES ('Hello', (SELECT ID FROM USERS WHERE LOGIN='Ellis'));

INSERT INTO MESSAGES(AUTHOR, ROOM, TEXT) VALUES((SELECT ID FROM USERS WHERE LOGIN='Alice'),
    (SELECT ID FROM CHATROOMS WHERE NAME='Java'), 'Hello!');
INSERT INTO MESSAGES(AUTHOR, ROOM, TEXT) VALUES ((SELECT ID FROM USERS WHERE LOGIN='Daisy'),
    (SELECT ID FROM CHATROOMS WHERE NAME='Java'), 'Hi!');
INSERT INTO MESSAGES(AUTHOR, ROOM, TEXT) VALUES ((SELECT ID FROM USERS WHERE LOGIN='Alice'),
    (SELECT ID FROM CHATROOMS WHERE NAME='Java'), 'How are you?');
INSERT INTO MESSAGES(AUTHOR, ROOM, TEXT) VALUES ((SELECT ID FROM USERS WHERE LOGIN='Daisy'),
    (SELECT ID FROM CHATROOMS WHERE NAME='Java'), 'I am fine and you?');
INSERT INTO MESSAGES(AUTHOR, ROOM, TEXT) VALUES ((SELECT ID FROM USERS WHERE LOGIN='Alice'),
    (SELECT ID FROM CHATROOMS WHERE NAME='Java'), 'I am good');

