INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Alice', 'hello');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Bob', 'world');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Chuck', 'hello_world');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Daisy', 'world_hello');
INSERT INTO USERS(LOGIN, PASSWORD) VALUES ('Ellis', 'hello');

INSERT INTO CHATROOM VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO CHATROOM VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO CHATROOM VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO CHATROOM VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO CHATROOM VALUES (100, 18, 'Zara', 'Ali');

INSERT INTO MESSAGE VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO MESSAGE VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO MESSAGE VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO MESSAGE VALUES (100, 18, 'Zara', 'Ali');
INSERT INTO MESSAGE VALUES (100, 18, 'Zara', 'Ali');
